# Gorelease comments public API changes to pull request.
name: gorelease
on:
  pull_request:

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GO_VERSION: stable
jobs:
  gorelease:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go stable
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Gorelease cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
        with:
          path: |
            ~/go/bin/gorelease
          key: ${{ runner.os }}-gorelease-generic
      - name: Gorelease
        id: gorelease
        run: |
          test -e ~/go/bin/gorelease || go install golang.org/x/exp/cmd/gorelease@latest
          OUTPUT=$(gorelease 2>&1 || exit 0)
          echo "${OUTPUT}"
          OUTPUT="${OUTPUT//$'\n'/%0A}"
          echo "report=$OUTPUT" >> $GITHUB_OUTPUT
      - name: Comment Report
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          header: gorelease
          message: |
            ### Go API Changes

            <pre>
            ${{ steps.gorelease.outputs.report }}
            </pre>
