# This script uploads application binaries as GitHub release assets.
name: release-assets
on:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable
          cache-dependency-path: go.sum
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build artifacts
        run: |
          make artifacts
      - name: Upload linux amd64 binary
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./_artifacts/godog-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          asset_name: godog-${{ github.event.release.tag_name }}-linux-amd64.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload linux arm64 binary
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./_artifacts/godog-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
          asset_name: godog-${{ github.event.release.tag_name }}-linux-arm64.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload darwin amd64 binary
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./_artifacts/godog-${{ github.event.release.tag_name }}-darwin-amd64.tar.gz
          asset_name: godog-${{ github.event.release.tag_name }}-darwin-amd64.tar.gz
          asset_content_type: application/tar+gzip
